import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
weather = pd.read_csv("Weather Dataset - Trial Activity DataSet.csv.csv")
print(weather.head(10))
print(weather.info())
sb.barplot(x="humidity",y = "temperature",data= weather)
plt.show()
sb.displot(weather["humidity"])
plt.show()
sb.jointplot(x="humidity",y = "temperature",data= weather)
plt.show()
sb.jointplot(x="humidity",y = "temperature",data= weather,kind="hex")
plt.show()
sb.jointplot(x="humidity",y = "temperature",data= weather,kind = "kde")
plt.show()
sb.pairplot(weather[["humidity","temperature","air_pollution_index"]])
plt.show()
sb.stripplot(x="weather_type",y = "temperature",data= weather)
plt.show()
sb.swarmplot(x="weather_type",y = "temperature",data= weather)
plt.show()
sb.barplot(x="humidity",y = "temperature",hue= "weather_type",data=weather)
plt.show()
sb.countplot(x="weather_type",data=weather)
plt.show()
sb.pointplot(x="humidity",y = "temperature",hue="weather_type",data=weather)
plt.show()